# Generated by Django 2.1.7 on 2019-06-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcoAlpsWater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPSampleDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_dirname', models.TextField(unique=True)),
                ('full_dirname', models.TextField(unique=True)),
                ('sample', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EcoAlpsWater.Sample')),
            ],
        ),
    ]
