# Generated by Django 2.1.7 on 2020-02-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoAlpsWater', '0003_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftpsampledirectory',
            name='sample',
        ),
        migrations.DeleteModel(
            name='FTPSampleDirectory',
        ),
    ]
