# Generated by Django 2.1.7 on 2020-03-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoAlpsWater', '0005_sequence_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sampling_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
