# Generated by Django 2.1.7 on 2020-03-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoAlpsWater', '0006_auto_20200317_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='eawuser',
            name='country',
            field=models.CharField(choices=[('Austria', 'A'), ('Switzerland', 'C'), ('France', 'F'), ('Germany', 'D'), ('Italy', 'I'), ('Slovenia', 'S')], default='Italy', max_length=11),
            preserve_default=False,
        ),
    ]
