# Generated by Django 2.1.7 on 2020-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoAlpsWater', '0007_eawuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='water_renewal_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
